name: qodo-merge-review
on:
  pull_request:
    types: [opened, reopened]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    name: Run PR Agent on every pull request and respond to comments
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Checkout external repo with Python script
        uses: actions/checkout@v3
        with:
          repository: uhc-tech-employer-individual/unet_comet_alt_auto_engineering_samples
          ref: pragntghecact
          path: external_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Azure Identity
        run: pip install azure-identity

      - name: Get Azure Token
        id: get_azure_token
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: python external_repo/get_azure_token.py

      - name: PR Agent action step
        id: pragent
        uses: uhc-tech-employer-individual/unet_comet_alt_auto_engineering_samples@pragntghecact
        env:
          LITELLM_LOG: "DEBUG"
          LITELLM_EXTRA_HEADERS: '{"projectId": "${{ secrets.AZURE_CLIENT_SECRET }}"}'
          OPENAI_API_TYPE: "azure_ad"
          OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
          AZURE_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_OPENAI_KEY: ${{ steps.get_azure_token.outputs.azure_openai_key }}
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_DEPLOYMENT_ID: ${{ vars.MODEL_DEPLOYMENT_ID }}
